package com.reps.app.data.exercise.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room mirror of the REPS dataset's Android export
 * (`database/reps_dataset/data/output/reps_offline.sqlite`).
 *
 * Table and column names follow the source export one-for-one so the two stay
 * diffable; the only additions are columns the SQLite export drops but the app
 * needs, and they are marked as such on each entity. Nothing is renamed, no ids
 * are rewritten, and no record is dropped - see `tools/build_exercise_db.py`.
 *
 * The whole catalogue is READ-ONLY on device. Nothing here has an insert or
 * update path: the file is regenerated by the pipeline and shipped whole.
 */
@Entity(
    tableName = "exercises",
    indices = [Index(value = ["category"])],
)
data class ExerciseEntity(
    @PrimaryKey
    @ColumnInfo(name = "id") val id: String,
    /** wger's numeric id, kept because every asset path is keyed by it. */
    @ColumnInfo(name = "external_id") val externalId: String,
    @ColumnInfo(name = "category") val category: String?,
    /** Shared by exercises that are variations of one another. */
    @ColumnInfo(name = "variation_group") val variationGroup: String?,
    @ColumnInfo(name = "license_name") val licenseName: String?,
    @ColumnInfo(name = "license_url") val licenseUrl: String?,
)

/**
 * One row per (exercise, language). All three of en/fr/ar are present for every
 * one of the 828 exercises, so a lookup never has to fall back.
 *
 * `name_folded` / `keywords_folded` are added by the converter: lowercased and
 * stripped of French accents and Arabic diacritics, so `LIKE` search matches
 * "developpe" against "Développé" and ignores tashkeel. The source export's
 * FTS5 table could not do this (see docs/android-integration.md).
 */
@Entity(
    tableName = "exercise_translations",
    primaryKeys = ["exercise_id", "language_code"],
    indices = [
        Index(value = ["language_code", "name_folded"]),
        Index(value = ["language_code", "name"]),
    ],
)
data class ExerciseTranslationEntity(
    @ColumnInfo(name = "exercise_id") val exerciseId: String,
    @ColumnInfo(name = "language_code") val languageCode: String,
    @ColumnInfo(name = "name") val name: String,
    @ColumnInfo(name = "name_folded") val nameFolded: String,
    @ColumnInfo(name = "summary") val summary: String,
    @ColumnInfo(name = "starting_position") val startingPosition: String,
    /** JSON arrays, exactly as the pipeline emitted them. */
    @ColumnInfo(name = "steps_json") val stepsJson: String,
    @ColumnInfo(name = "tips_json") val tipsJson: String,
    @ColumnInfo(name = "notes_json") val notesJson: String,
    @ColumnInfo(name = "keywords_json") val keywordsJson: String,
    @ColumnInfo(name = "keywords_folded") val keywordsFolded: String,
)

@Entity(
    tableName = "exercise_muscles",
    primaryKeys = ["exercise_id", "muscle_name", "role"],
    indices = [Index(value = ["exercise_id"]), Index(value = ["muscle_name"])],
)
data class ExerciseMuscleEntity(
    @ColumnInfo(name = "exercise_id") val exerciseId: String,
    /** Anatomical name, e.g. "Latissimus dorsi". Joins to `muscle_svg_assets`. */
    @ColumnInfo(name = "muscle_name") val muscleName: String,
    /** Common name, e.g. "Lats". Null for the 5 muscles wger never gave one. */
    @ColumnInfo(name = "name_en") val nameEn: String?,
    /** `primary` or `secondary`. */
    @ColumnInfo(name = "role") val role: String,
    @ColumnInfo(name = "is_front") val isFront: Boolean?,
)

@Entity(
    tableName = "exercise_equipment",
    primaryKeys = ["exercise_id", "equipment_name"],
    indices = [Index(value = ["exercise_id"]), Index(value = ["equipment_name"])],
)
data class ExerciseEquipmentEntity(
    @ColumnInfo(name = "exercise_id") val exerciseId: String,
    @ColumnInfo(name = "equipment_name") val equipmentName: String,
)

@Entity(
    tableName = "exercise_aliases",
    primaryKeys = ["exercise_id", "alias"],
    indices = [Index(value = ["exercise_id"])],
)
data class ExerciseAliasEntity(
    @ColumnInfo(name = "exercise_id") val exerciseId: String,
    @ColumnInfo(name = "alias") val alias: String,
)

/**
 * Demonstration media. These files are the ~208 MB the app deliberately does
 * NOT ship: only the references live here.
 *
 * `asset_path` is the pipeline's CDN-relative key (`assets/exercises/1000/main.png`);
 * `remote_url` is the live source URL the pipeline downloaded from, which the
 * SQLite export drops and the converter restores from `reps_exercises_clean.json`.
 * Which one wins at runtime is [com.reps.app.data.exercise.MediaUrlResolver]'s call.
 */
@Entity(
    tableName = "exercise_images",
    indices = [Index(value = ["exercise_id"])],
)
data class ExerciseImageEntity(
    @PrimaryKey
    @ColumnInfo(name = "id") val id: String,
    @ColumnInfo(name = "exercise_id") val exerciseId: String,
    @ColumnInfo(name = "is_main") val isMain: Boolean,
    @ColumnInfo(name = "asset_path") val assetPath: String?,
    @ColumnInfo(name = "remote_url") val remoteUrl: String?,
    /** wger's 200x200 render - what list rows should ask for. */
    @ColumnInfo(name = "thumb_small_url") val thumbSmallUrl: String?,
    /** wger's 400x400 render. */
    @ColumnInfo(name = "thumb_medium_url") val thumbMediumUrl: String?,
    @ColumnInfo(name = "width") val width: Int?,
    @ColumnInfo(name = "height") val height: Int?,
    /**
     * Stable display order within an exercise, assigned by the converter.
     * 10 exercises carry more than one `is_main` row upstream, so is_main alone
     * is not a deterministic sort.
     */
    @ColumnInfo(name = "sort_order") val sortOrder: Int,
)

/**
 * The per-muscle overlay SVGs - two variants (`main`, `secondary`) for each of
 * the 15 muscles. Small (~3 KB each), so unlike the demonstration images these
 * DO ship inside the APK, under `assets/svg/`.
 */
@Entity(
    tableName = "muscle_svg_assets",
    primaryKeys = ["muscle_name", "variant"],
)
data class MuscleSvgAssetEntity(
    @ColumnInfo(name = "muscle_name") val muscleName: String,
    /** `main` (primary-muscle tint) or `secondary`. */
    @ColumnInfo(name = "variant") val variant: String,
    /** Path inside the APK's assets/, e.g. `svg/muscles/main/muscle-4.svg`. */
    @ColumnInfo(name = "asset_path") val assetPath: String,
    @ColumnInfo(name = "width") val width: Int?,
    @ColumnInfo(name = "height") val height: Int?,
)

/** The front/back body illustrations the muscle overlays stack on top of. */
@Entity(tableName = "body_diagrams")
data class BodyDiagramEntity(
    @PrimaryKey
    @ColumnInfo(name = "side") val side: String,
    @ColumnInfo(name = "asset_path") val assetPath: String,
    @ColumnInfo(name = "width") val width: Int?,
    @ColumnInfo(name = "height") val height: Int?,
)
