package com.reps.app.core.svg

import android.graphics.Matrix
import android.graphics.Path
import androidx.core.graphics.PathParser

/**
 * Extracts drawable geometry from the catalogue's muscle-overlay SVGs.
 *
 * These files are machine-generated by the dataset pipeline and share one
 * shape: a root `<g>` carrying an Inkscape `translate(...)`, holding every
 * muscle's `<path>` elements in absolute document coordinates. Splitting the
 * pure string extraction from the android.graphics work keeps the parsing
 * logic testable on the JVM.
 *
 * Only what the overlays actually use is supported - no CSS, no nested
 * transforms, no shapes other than `<path>`. Anything unexpected degrades to
 * fewer drawn shapes rather than an error.
 */
object OverlaySvg {

    /** One overlay's geometry in its own canvas units (typically 200x369). */
    data class Geometry(
        val translateX: Float,
        val translateY: Float,
        val canvasWidth: Float,
        val canvasHeight: Float,
        val pathData: List<String>,
    )

    /**
     * Parses [svgText] into geometry, or null when it carries no path data.
     * A missing translate means the artwork was authored in canvas coordinates
     * already; a missing size falls back to the catalogue's standard canvas.
     */
    fun geometry(svgText: String): Geometry? {
        val pathData = D_ATTR_REGEX.findAll(svgText)
            .mapNotNull { it.groupValues[1].takeIf(String::isNotBlank) }
            .toList()
        if (pathData.isEmpty()) return null

        val translate = TRANSLATE_REGEX.find(svgText)
        return Geometry(
            translateX = translate?.groupValues?.get(1)?.toFloatOrNull() ?: 0f,
            translateY = translate?.groupValues?.get(2)?.toFloatOrNull() ?: 0f,
            canvasWidth = WIDTH_REGEX.find(svgText)?.groupValues?.get(1)?.toFloatOrNull()
                ?: DEFAULT_CANVAS_WIDTH,
            canvasHeight = HEIGHT_REGEX.find(svgText)?.groupValues?.get(1)?.toFloatOrNull()
                ?: DEFAULT_CANVAS_HEIGHT,
            pathData = pathData,
        )
    }

    /**
     * Materialises [geometry] as translated android paths ready to draw at
     * canvas coordinates. Unparseable path data costs its own shape only -
     * wger's artwork never varies mid-file.
     */
    fun toPaths(geometry: Geometry): List<Path> = geometry.pathData.mapNotNull { d ->
        runCatching {
            PathParser.createPathFromPathData(d)?.apply {
                transform(Matrix().apply { postTranslate(geometry.translateX, geometry.translateY) })
            }
        }.getOrNull()
    }

    private const val DEFAULT_CANVAS_WIDTH = 200f
    private const val DEFAULT_CANVAS_HEIGHT = 369f

    // Whitespace-anchored so sibling attributes like `id="path1234"` - which
    // every Inkscape-authored overlay carries - never read as path data.
    private val D_ATTR_REGEX = Regex("\\sd=\"([^\"]+)\"")
    private val TRANSLATE_REGEX = Regex("""translate\(\s*(-?[\d.]+)[\s,]+(-?[\d.]+)\s*\)""")
    private val WIDTH_REGEX = Regex("width=\"([\\d.]+)\"")
    private val HEIGHT_REGEX = Regex("height=\"([\\d.]+)\"")
}
